parameters:
    database_driver:   pdo_mysql
    database_host:     mysql-178723.vipserv.org
    database_port:     
    database_name:     akopec_karol
    database_user:     akopec_karol
    database_password: karolmgr

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       
    mailer_password:   

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
